language: python
python:
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
install:
 - pip install nose
 - pip install coveralls
 # coverage no longer supports python 3.2...
 # - pip install coverage
 - if [ "$TRAVIS_PYTHON_VERSION" == "3.2" ]; then travis_retry pip install coverage==3.7.1; fi
 - if [ "$TRAVIS_PYTHON_VERSION" != "3.2" ]; then travis_retry pip install coverage; fi
script:
 - nosetests
 - coverage run -m nose
after_success:
 - coveralls
